### ISSUE TITLE
Semantics: Add <article> element

### ISSUE THREAD

**Issue by swordfischer** [SteamLUG/steamlug.org#115]
As per #96 `<article>` elements needs to be created.

**Comment by johndrinkwater** [comment]
Along with this, let’s use <nav> rather than <div class="navbar-default navbar-bottom">

**Comment by Cheeseness** [comment]
> Along with this, let’s use nav rather than div class="navbar-default navbar-bottom".

This gets my +1, but as far as I understand the rationale behind bootstrap, the idea is that you apply classes regardless of semantic markup so that you can make anything appear as anything else (I think we'd still need to use the same classnames).

@swordfischer can you correct me there if I'm wrong?

**Comment by swordfischer** [comment]
I believe some of the classes are dependent on the element (some styles might color p and div differently for instance, with the same class).
But it looks like most of the stuff you want can be done with same classes, different elements

**Comment by johndrinkwater** [comment]
With the PR of #118, this was closed.
