### ISSUE TITLE
Site Redesign (Bootstrap?)

### ISSUE THREAD

**Issue by swordfischer** [SteamLUG/steamlug.org#96]
As per #29 we've talked about site redesign.

In the initial phase I propose modify the site to use [BootStrap](http://getbootstrap.com/).
This will allow us to change themes easily and create our own.

I'm currently doing so, and have converted everything besides the cast page.

Thoughts?

**Comment by swordfischer** [comment]
Note: Add Article Element

**Comment by swordfischer** [comment]
Haven't added Article elements yet.

https://github.com/swordfischer/steamlug.org/tree/BootStrap

We need to seriously go through formatting and shit.. I have one issue left though - unknown index for the 3 decisions (L515-517 functions_poll.php)

Dunno how to fix that.

http://swordfischer.com:4000/polls.php

**Comment by Cheeseness** [comment]
> http://swordfischer.com:4000/polls.php

This isn't working for me.

**Comment by swordfischer** [comment]
So the site currently looks like 'it should', with some minor issues with the poll admin page.
I'd prefer if we soon merged the changes, then put up another issue to resolve that, and then take a look at general formatting throughout the code (NOT HERE!)

**Comment by Cheeseness** [comment]
I'll make time to look over this in more detail tomorrow. A quick skim shows a bunch of stuff that's no longer in article tags but should be. It'd be nice, but not essential to get that sorted first.

The countdown timer elements look like they've got button like behaviour (button style hover effects and an action cursor) - is that intentional?

**Comment by swordfischer** [comment]
Haven't added `<article>` tags, and somone who knows how they are used can do that.

Yes it's intentional.

**Comment by Cheeseness** [comment]
The current site is a great reference for where <article> tags are used. It's OK to just put them back where they were originally without any knowledge of how they're meant to be used (they behave exactly as <div> tags so far as styles are concerned).

Can you explain why button-like behaviour is intentional? It doesn't make any sense to me.

**Comment by swordfischer** [comment]
I'll wait with `<article>` stuff until bootstrap has been merged. It doesn't break anything **not** having it.

Because that is the bootstrap default for buttons. It can be fixed quickly if we set the disabled property for those buttons.
http://getbootstrap.com/css/#buttons-disabled

**Comment by swordfischer** [comment]
#114
